import type { GlobalThemeOverrides } from 'naive-ui'

export const themeOverrides: GlobalThemeOverrides = {
  common: {
    primaryColor: '#ff0000',
    primaryColorHover: '#d70000',
    primaryColorPressed: '#b10303',
    primaryColorSuppl: '#ff2323',
    infoColor: '#ff0000',
    infoColorHover: '#d70000',
    infoColorPressed: '#b10303',
    infoColorSuppl: '#ff2323',
    successColor: '#ff0000',
    successColorHover: '#d70000',
    successColorPressed: '#b10303',
    successColorSuppl: '#ff2323',
    warningColor: '#ff0000',
    warningColorHover: '#d70000',
    warningColorPressed: '#b10303',
    warningColorSuppl: '#ff2323',
    errorColor: '#ff0000',
    errorColorHover: '#d70000',
    errorColorPressed: '#b10303',
    errorColorSuppl: '#ff2323',
  },
  Button: {
    textColor: '#ffffff',
    textColorHover: '#ffffff',
    textColorPressed: '#ffffff',
    textColorFocus: '#ffffff',
    textColorDisabled: '#ff9494',
    color: '#ff0000',
    colorHover: '#d70000',
    colorPressed: '#b10303',
    colorFocus: '#ff2323',
    colorDisabled: '#ff9494',
    border: '1px solid #ff0000',
    borderHover: '1px solid #d70000',
    borderPressed: '1px solid #b10303',
    borderFocus: '1px solid #ff2323',
    borderDisabled: '1px solid #ff9494',
    rippleColor: '#ff2323',
    textColorGhost: '#ff0000',
    textColorGhostHover: '#d70000',
    textColorGhostPressed: '#b10303',
    textColorGhostFocus: '#ff2323',
    textColorGhostDisabled: '#ff9494',
    colorGhost: 'transparent',
    colorGhostHover: '#fff0f0',
    colorGhostPressed: '#ffdddd',
    colorGhostFocus: '#fff0f0',
    colorGhostDisabled: 'transparent',
    borderGhost: '1px solid #ff0000',
    borderGhostHover: '1px solid #d70000',
    borderGhostPressed: '1px solid #b10303',
    borderGhostFocus: '1px solid #ff2323',
    borderGhostDisabled: '1px solid #ff9494',
  },
  Card: {
    color: '#ffffff',
    colorModal: '#ffffff',
    colorEmbedded: '#ffffff',
    colorEmbeddedModal: '#ffffff',
    colorEmbeddedPopover: '#ffffff',
    textColor: '#000000',
    titleTextColor: '#000000',
    borderColor: '#ff0000',
    actionColor: '#ff0000',
  },
  Menu: {
    itemTextColor: '#000000',
    itemTextColorHover: '#ff0000',
    itemTextColorActive: '#ff0000',
    itemTextColorActiveHover: '#d70000',
    itemTextColorChildActive: '#ff0000',
    itemTextColorChildActiveHover: '#d70000',
    itemIconColor: '#000000',
    itemIconColorHover: '#ff0000',
    itemIconColorActive: '#ff0000',
    itemIconColorActiveHover: '#d70000',
    itemIconColorChildActive: '#ff0000',
    itemIconColorChildActiveHover: '#d70000',
    itemColor: '#ffffff',
    itemColorActive: '#fff0f0',
    itemColorActiveHover: '#ffdddd',
    itemColorActiveCollapsed: '#fff0f0',
    itemColorActiveHoverCollapsed: '#ffdddd',
    itemColorChildActive: '#fff0f0',
    itemColorChildActiveHover: '#ffdddd',
    itemBorderRadius: '4px',
  },
}
